Adds support for Dyson HP04 Model
etheralm/libpurecool pull request #5
Opened 2019-06-23 03:25 UTC by Parlane

HP04 is an air purifier and and heater/fan. HP04 uses v2 of the api.

2019-06-23 03:35 UTC, Parlane commented
This fixes issue 4

2019-06-23 05:05 UTC, Parlane commented
Sorry, this needs more work to make it compatible with homeassistant.

2019-06-23 05:11 UTC, Parlane commented
`
AttributeError: 'DysonEnvironmentalSensorV2State' object has no attribute 'dust'


AttributeError: 'DysonEnvironmentalSensorV2State' object has no attribute 'volatil_organic_compounds'


AttributeError: 'DysonPureHotCoolV2State' object has no attribute 'filter_life'


AttributeError: 'DysonPureHotCoolV2State' object has no attribute 'focus_mode'


AttributeError: 'DysonPureHotCoolV2State' object has no attribute 'fan_mode'
`

2019-07-02 15:58 UTC, etheralm commented
Hi, thanks a  lot for the pr, looks good on a first glance. Sorry about the late response I just came back from vacation. I'll have deeper look when I get the time and I'll get back to you.

2019-07-12 03:54 UTC, itssimon commented
I have two HP04 devices at home in case you need any help with testing!

2019-08-04 20:36 UTC, ryanrhughes commented
I'm not sure if it's helpful for review or not but I managed to get @Parlane's update working with the Home Assistant component. https://github.com/ryanrhughes/home-assistant/commit/5533ade0e60f41ad2f091af76c0ba4788c468394

2019-08-05 10:15 UTC, etheralm commented on libpurecool/dyson_pure_state_v2.py
> +                                                                'hmax')
Ident is wrong, please align it with 'self' on the line above

2019-08-05 10:15 UTC, etheralm commented on libpurecool/dyson_pure_state_v2.py
> +                                                              'hmod')
Same as above

2019-08-05 10:16 UTC, etheralm commented on libpurecool/dyson_pure_state_v2.py
> +                                                               'hsta')
Same as above

2019-08-05 10:22 UTC, etheralm commented on libpurecool/dyson_pure_state_v2.py
> +        else:
Please remove the else.

2019-08-05 10:23 UTC, etheralm commented on libpurecool/dyson_pure_state_v2.py
> +        else:
Please remove the last else here

2019-08-05 10:32 UTC, etheralm requested changes
Hi, thanks a lot for your submission. I'm really sorry for the horribly late response, I was on the move since you submitted it and didn't have the opportunity to check if everything still works OK with the other models.

Your changes look great, I've only added a few comments about a few things that popped  out of the pylint check. Apart from that, the changes in the PR are missing tests for them and it would be nice if you can write them, but I would accept it even if they are not ready as not to postpone the update any more and I'll add them later in another update.

Cheers

2019-08-05 11:30 UTC, etheralm commented
> 
> 
> I'm not sure if it's helpful for review or not but I managed to get @Parlane's update working with the Home Assistant component. [ryanrhughes/home-assistant@5533ade](https://github.com/ryanrhughes/home-assistant/commit/5533ade0e60f41ad2f091af76c0ba4788c468394)
@ryanrhughes thx, I just tested his changes, with HA and the fan model that I have (DP04), just to be sure and it seems to work fine. Glad to hear that HA is working also with HP04. 

I'll try to push the new version to pypi until the end of the week and then to get it working officially in ha afterwards.

2019-08-06 09:30 UTC, Parlane commented
Give me until the end of the week to fix this up as there were some issues still integrating with home assistant. Mostly that the climate control doesn't apply setting changes. And I possibly broke backwards compatibility with other v2 devices.

2019-08-06 09:36 UTC, etheralm commented
np take your time, let me know if I can help with anything.

2019-08-16 16:33 UTC, lwis commented
@Parlane anything I can do to help you get this merged? I know a few people are keen to get HP04 support in HA.

2019-08-16 23:10 UTC, Parlane commented
Looking at it now.

2019-08-16 23:21 UTC, Parlane commented
Fixed the code review notes, but working on the HA integration isuses now.

2019-08-17 05:11 UTC, Parlane commented
With the current changes it does seem the climate device "works, but if you compare it to my heat pump you can see it doesn't support the OFF mode. In the image below it says it is cooling but it is actually turned off currently.

![image](https://user-images.githubusercontent.com/86614/63206922-dbef2b00-c111-11e9-8dbd-a1a4cd83f739.png)

2019-08-17 05:14 UTC, Parlane commented
The way I am testing this is by going in to the custom_components directory and doing:

git clone https://github.com/Parlane/ha_dyson.git dyson

This overrides the built in dyson component.

2019-08-17 09:48 UTC, Parlane commented
OK under https://github.com/Parlane/ha_dyson/commit/66cdab975fba0d854ab2956d7cfdc6ee5acc2d73 I have made the changes required in home assistant to support this work.

The only worry I have is that I needed to add fpwr to DysonPureHotCoolLink, which I worry will break pre-hp04 dyson devices. Maybe it might need another subclass just for hp04 ?

I only have an hp04 to test with.

2019-08-18 06:45 UTC, lwis commented
@Parlane iJust tested using your custom component on my HP04;

- Fan isn't working, I can set the fan speed, but I'm unable to turn it on/change oscillation/change to auto.
- Climate looks good now, can switch hot/cool/off perfectly.
- Are you seeing VoC/p10/p25/NO2 in HA?

2019-08-18 19:43 UTC, Parlane commented
I will have a look at the fan module tonight, I've never tried it to be honest...

The VoC etc are not added to sensor.py: https://github.com/Parlane/ha_dyson/blob/master/sensor.py

These could be added as additional sensors.

There is dust support existing which I added to EnvironmentV2, it uses max(self._particulate_matter_25, self._particulate_matter_10) provided by DysonDustSensor

VoC is provided by DysonAirQualitySensor

I tried to make the least changes to HA as possible just to make it easier to test, thats why I added a lot of backwards compat functions such as dust :)

2019-08-18 20:04 UTC, Parlane commented
![image](https://user-images.githubusercontent.com/86614/63229755-fd5a2f00-c257-11e9-8ee3-2a63e5192cbf.png)

2019-08-19 08:18 UTC, lwis commented
@Parlane gotcha, I see that the data is exposed from the lib - we can enhance HA in the future.

2019-09-04 20:57 UTC, honeyworld2 commented
> @Parlane Just tested using your custom component on my HP04;
> 
> * Fan isn't working, I can set the fan speed, but I'm unable to turn it on/change oscillation/change to auto.
> * Climate looks good now, can switch hot/cool/off perfectly.
> * Are you seeing VoC/p10/p25/NO2 in HA?

Hi all, thanks for your great work! Any progress with turning on/off the Fan / Auto Mode... ?

2019-10-20 06:10 UTC, canthefason commented
These two PRs will fix the fan auto mode issue. PTAL.

https://github.com/Parlane/libpurecool/pull/1
https://github.com/Parlane/ha_dyson/pull/1

2019-10-21 13:41 UTC, brott8 commented
@Parlane , looks great, thanks for the work you put into it.
Just a quick one, I think your Air Quality sensor is referencing the incorrect environmental_state.  "volatil_organic_compounds" should be the VOC sensor.

I guess the AQI would be the max of the other sensors as defined in air_quality.py.
I'll give it a try later.

2019-12-02 17:57 UTC, FutureGUIs commented
Any extra help needed here?  I just got a hp04 and really would like this PR pushed through.  I've got 2 hp02's as well if we just need testing and/or coding help too.

2019-12-05 15:54 UTC, etheralm commented
Hey everyone, sorry that this is taking so long. I have a bit of a free time right now and I intend to get this finally done. 

I've created a new branch [here](https://github.com/etheralm/libpurecool/tree/new_hot_cool).  You can track the progress there. So far I haven't made any changes but I plan to cobble up an initial version tomorrow or on Saturday. I'll also try to create a short script to test if everything works properly which I would ask you to run since I don't have that model and can't test it myself. Stay tuned.

2019-12-08 21:05 UTC, etheralm commented
OK I think I'm ready with the needed changes.  I've posted instructions how to test them in the issue ticket https://github.com/etheralm/libpurecool/issues/4

I'll close this PR for now, lets continue the discussion there as to not have it in multiple places at the same time.

2019-12-08 21:05 UTC, closed without merging

2019-12-09 01:33 UTC, FutureGUIs commented
Well, I'm not all up on python that much yet, but my regular hp02 devices seem to connect and send/get data just fine from the logging I see, but my hp04 doesn't even connect, even trying to manually connect using its IP address...  I get no logging either with the hp04